// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "API PERSONAS",
    "version": "1.0.0",
    "description": "Esta API esta desarrollado con Serverless Framework en NodeJs y desplegado en AWS. Desarrollado por Orlando Netty Yarasca Lupuche"
  },
  "paths": {
    "/persona/": {
      "get": {
        "summary": "getAllPersonas",
        "description": "",
        "operationId": "getAllPersonas.get.persona/",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/persona": {
      "post": {
        "summary": "createPersona",
        "description": "",
        "operationId": "createPersona.post.persona",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/vehiculoSwapi/": {
      "get": {
        "summary": "getAllVehiculosSwapi",
        "description": "",
        "operationId": "getAllVehiculosSwapi.get.vehiculoSwapi/",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "VehiculoEsResponse": {
      "properties": {
        "nombre": {
          "title": "VehiculoEsResponse.nombre",
          "type": "string"
        },
        "modelo": {
          "title": "VehiculoEsResponse.modelo",
          "type": "string"
        },
        "creado": {
          "title": "VehiculoEsResponse.creado",
          "type": "string"
        },
        "editado": {
          "title": "VehiculoEsResponse.editado",
          "type": "string"
        },
        "url": {
          "title": "VehiculoEsResponse.url",
          "type": "string"
        }
      },
      "required": [
        "nombre",
        "modelo",
        "creado",
        "editado",
        "url"
      ],
      "additionalProperties": false,
      "title": "VehiculoEsResponse",
      "type": "object"
    },
    "VehiculoResponse": {
      "properties": {
        "name": {
          "title": "VehiculoResponse.name",
          "type": "string"
        },
        "model": {
          "title": "VehiculoResponse.model",
          "type": "string"
        },
        "created": {
          "title": "VehiculoResponse.created",
          "type": "string"
        },
        "edited": {
          "title": "VehiculoResponse.edited",
          "type": "string"
        },
        "url": {
          "title": "VehiculoResponse.url",
          "type": "string"
        }
      },
      "required": [
        "name",
        "model",
        "created",
        "edited",
        "url"
      ],
      "additionalProperties": false,
      "title": "VehiculoResponse",
      "type": "object"
    },
    "Persona": {
      "properties": {
        "id": {
          "title": "Persona.id",
          "type": "string"
        },
        "nombres": {
          "title": "Persona.nombres",
          "type": "string"
        },
        "apellidos": {
          "title": "Persona.apellidos",
          "type": "string"
        },
        "genero": {
          "title": "Persona.genero",
          "type": "string"
        },
        "fnacimiento": {
          "title": "Persona.fnacimiento",
          "type": "string"
        },
        "estado": {
          "title": "Persona.estado",
          "type": "boolean"
        },
        "creado": {
          "title": "Persona.creado",
          "type": "string"
        }
      },
      "required": [
        "id",
        "nombres",
        "apellidos",
        "genero",
        "fnacimiento",
        "estado",
        "creado"
      ],
      "additionalProperties": false,
      "title": "Persona",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev"
};